/*
 * @Descripttion: 
 * @Date: 2022-08-10 11:28:44
 * @LastEditTime: 2022-11-23 16:04:29
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
}
export { }
